apiVersion: v1
kind: Template
labels:
  template: route
message: 'A new route has been created for your service'
metadata:
  annotations:
    iconClass: icon-app
  name: route
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    port:
      targetPort: ${TARGET_PORT}
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
- description: The service port to route traffic.
  displayName: target Port
  name: TARGET_PORT
  required: true
  value: 8080-tcp